-- Run inside BEGIN/ROLLBACK; all identities and the extra booking are synthetic.
do $$
declare s1 uuid:=gen_random_uuid(); s2 uuid:=gen_random_uuid(); adm uuid:=gen_random_uuid(); ordinary uuid:=gen_random_uuid();
  bid bigint; aid uuid; rid uuid; result jsonb;
begin
  insert into auth.users(id,raw_app_meta_data,raw_user_meta_data) values
    (s1,'{"role":"staff"}','{"fullName":"Synthetic Requester"}'),
    (s2,'{"role":"staff"}','{"fullName":"Synthetic Other Staff"}'),
    (adm,'{"role":"admin"}','{"fullName":"Synthetic Reviewer"}'),
    (ordinary,'{}','{"role":"admin"}');
  select coalesce(max(id),0)+1000000 into bid from public.bookings;
  insert into public.bookings select (jsonb_populate_record(null::public.bookings,to_jsonb(b)||jsonb_build_object('id',bid,'status','cancelled','internalNote','Synthetic original note'))).* from public.bookings b where b.id=518;
  if not found then raise exception 'Synthetic booking source missing'; end if;
  perform set_config('request.jwt.claim.sub',s1::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',s1,'app_metadata',jsonb_build_object('role','staff'))::text,true);
  set local role authenticated;
  select approval_id into aid from public.create_booking_ai_approval(bid,'Synthetic requested note');
  if (select status from public.booking_ai_approvals where id=aid)<>'draft' then raise exception 'draft not persisted'; end if;
  if (select "internalNote" from public.bookings where id=bid)<>'Synthetic original note' then raise exception 'draft wrote booking'; end if;
  result:=public.transition_booking_ai_approval(aid,'submit','submit-workflow-fixture-1');
  if result->>'status'<>'pending' then raise exception 'submission failed'; end if;
  begin perform public.transition_booking_ai_approval(aid,'approve','forged-staff-decision-1'); raise exception 'staff approve allowed'; exception when insufficient_privilege then null; end;
  begin perform public.decide_booking_internal_note(aid,'approve','forged-legacy-decision-1'); raise exception 'legacy staff approve allowed'; exception when insufficient_privilege then null; end;
  begin perform public.list_booking_ai_approvals('inbox'); raise exception 'staff inbox allowed'; exception when insufficient_privilege then null; end;
  begin update public.booking_ai_approvals set status='executed' where id=aid; raise exception 'direct client write allowed'; exception when insufficient_privilege then null; end;
  reset role;
  perform set_config('request.jwt.claim.sub',s2::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',s2,'app_metadata',jsonb_build_object('role','staff'))::text,true);
  set local role authenticated;
  if exists(select 1 from public.booking_ai_approvals where id=aid) then raise exception 'cross-staff RLS leak'; end if;
  begin perform public.transition_booking_ai_approval(aid,'cancel','cross-staff-cancel-1'); raise exception 'cross-staff cancel allowed'; exception when insufficient_privilege then null; end;
  reset role;
  perform set_config('request.jwt.claim.sub',adm::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',adm,'app_metadata',jsonb_build_object('role','admin'))::text,true);
  set local role authenticated;
  result:=public.list_booking_ai_approvals('inbox','pending');
  if not exists(select 1 from jsonb_array_elements(result->'items') item where item->>'id'=aid::text) then raise exception 'administrator inbox missing request'; end if;
  result:=public.transition_booking_ai_approval(aid,'approve','admin-workflow-decision-1');
  if result->>'status'<>'executed' then raise exception 'administrator decision failed'; end if;
  result:=public.transition_booking_ai_approval(aid,'approve','admin-workflow-decision-1');
  if result->>'repeated'<>'true' then raise exception 'repeat not idempotent'; end if;
  if (select count(*) from public.booking_ai_audit_log where approval_id=aid and event='executed')<>1 then raise exception 'duplicate execution'; end if;
  if (select "internalNote" from public.bookings where id=bid)<>'Synthetic requested note' then raise exception 'note not saved'; end if;
  reset role;
  perform set_config('request.jwt.claim.sub',s1::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',s1,'app_metadata',jsonb_build_object('role','staff'))::text,true);
  set local role authenticated;
  if not exists(select 1 from public.booking_ai_audit_log where approval_id=aid and event='approved') then raise exception 'requester cannot see reviewer audit'; end if;
  if (public.list_booking_ai_approvals('mine')->>'unreadCount')::int<>1 then raise exception 'persistent result notification missing'; end if;
  perform public.transition_booking_ai_approval(aid,'acknowledge','read-workflow-result-1');
  if (public.list_booking_ai_approvals('mine')->>'unreadCount')::int<>0 then raise exception 'result unread state not cleared'; end if;
  select approval_id into rid from public.create_booking_ai_approval(bid,'Synthetic rejected draft');
  perform public.transition_booking_ai_approval(rid,'submit','submit-rejection-fixture-1');
  reset role;
  perform set_config('request.jwt.claim.sub',adm::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',adm,'app_metadata',jsonb_build_object('role','admin'))::text,true);
  set local role authenticated;
  begin perform public.transition_booking_ai_approval(rid,'reject','reject-no-reason-fixture-1'); raise exception 'empty rejection reason accepted'; exception when raise_exception then if sqlerrm<>'rejection reason required' then raise; end if; end;
  result:=public.transition_booking_ai_approval(rid,'reject','reject-workflow-fixture-1','Needs correction');
  if result->>'status'<>'rejected' or (select "internalNote" from public.bookings where id=bid)<>'Synthetic requested note' then raise exception 'rejection changed booking'; end if;
  reset role;
  perform set_config('request.jwt.claim.sub',s1::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',s1,'app_metadata',jsonb_build_object('role','staff'))::text,true);
  set local role authenticated;
  select approval_id into rid from public.create_booking_ai_approval(bid,'Synthetic stale draft');
  perform public.transition_booking_ai_approval(rid,'submit','submit-conflict-fixture-1');
  reset role;
  update public.bookings set "internalNote"='Synthetic newer note' where id=bid;
  perform set_config('request.jwt.claim.sub',adm::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',adm,'app_metadata',jsonb_build_object('role','admin'))::text,true);
  set local role authenticated;
  result:=public.transition_booking_ai_approval(rid,'approve','conflict-workflow-fixture-1');
  if result->>'status'<>'conflict' or (select "internalNote" from public.bookings where id=bid)<>'Synthetic newer note' then raise exception 'stale note overwritten'; end if;
  if exists(select 1 from public.booking_ai_audit_log where approval_id=rid and event='executed') then raise exception 'conflict marked executed'; end if;
  reset role;
  perform set_config('request.jwt.claim.sub',s1::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',s1,'app_metadata',jsonb_build_object('role','staff'))::text,true);
  set local role authenticated;
  select approval_id into rid from public.create_booking_ai_approval(bid,'Synthetic withdrawn draft');
  perform public.transition_booking_ai_approval(rid,'submit','submit-withdraw-fixture-1');
  result:=public.transition_booking_ai_approval(rid,'cancel','cancel-workflow-fixture-1');
  if result->>'status'<>'cancelled' then raise exception 'withdrawal failed'; end if;
  reset role;
  perform set_config('request.jwt.claim.sub',ordinary::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',ordinary,'user_metadata',jsonb_build_object('role','admin'))::text,true);
  set local role authenticated;
  begin perform public.list_booking_ai_approvals('inbox'); raise exception 'spoofed metadata accepted'; exception when insufficient_privilege then null; end;
  reset role;
end; $$;
