import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tool } from "ai";
import { z } from "zod";
import { createConciergeAgent, CONCIERGE_INSTRUCTIONS } from "@/app/_ai/agents/concierge-agent";
import { resolveConciergeProviderConfiguration } from "@/app/_ai/providers/concierge-model";
import { createCabinTools } from "@/app/_ai/tools/cabin-tools";
import { createEvaluationDataSource } from "../ai/evals/concierge-fixture";
import { createRunObserver, type RunRecord } from "@/app/_ai/observability/run";
import { issueFeedbackToken } from "@/app/_ai/observability/access";
import { POST as feedback } from "@/app/api/ai/feedback/route";
import { createPrivilegedSupabaseClient } from "@/app/_lib/supabase-server";
import { assessLiveResult, liveCases } from "./assertions";
import { safeErrorDiagnostic } from "./error-diagnostic";

function percentile(values: number[], p: number) { const sorted = [...values].sort((a,b) => a-b); return sorted.length ? sorted[Math.max(0, Math.ceil(sorted.length*p)-1)] : null; }
function priceConfig() {
  if (!process.env.AI_PRICE_FILE) return null;
  const value = JSON.parse(readFileSync(process.env.AI_PRICE_FILE, "utf8"));
  return z.object({ asOf: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), source: z.string().url(), models: z.record(z.string(), z.object({ inputPerMillion: z.number().nonnegative(), outputPerMillion: z.number().nonnegative() })) }).parse(value);
}
it("runs selected fixed live-model scenarios with fixture business tools and real dev telemetry", async () => {
  expect(process.env.AI_EVAL_LIVE).toBe("1");
  const requested = process.env.AI_EVAL_CASES?.split(",").filter(Boolean) ?? [];
  if (requested.some(id => !liveCases.some(row => row.id === id))) throw new Error("Unknown fixed live scenario ID");
  const selectedCases = requested.length ? liveCases.filter(row => requested.includes(row.id)) : liveCases;
  const configuration = resolveConciergeProviderConfiguration(), prices = priceConfig(), db = createPrivilegedSupabaseClient();
  const results: Array<{ id: string; passed: boolean; checks: Record<string, boolean>; failures: string[]; diagnostic: ReturnType<typeof safeErrorDiagnostic> | null; run: RunRecord; persisted: boolean; feedbackSaved: boolean; costUSD: number | null }> = [];
  const folder = "tests/ai/reports/live"; mkdirSync(folder, { recursive: true });
  const stamp = new Date().toISOString().replaceAll(":", "-");
  let activeScenario: string | null = null;
  const saveReport = () => {
    const report = { schemaVersion: 3, generatedAt: new Date().toISOString(), mode: "live-model-fixture-business-tools-real-dev-telemetry", configuration, catalogCount: liveCases.length, selectedScenarioIds: selectedCases.map(row => row.id), priceSource: prices ? { asOf: prices.asOf, source: prices.source } : null, limitations: ["Synthetic inventory and policy tools; not embedding quality or production database business validation", "Answer checks are deterministic heuristics; not a semantic judge", "Feedback rating is generated by the harness; not user satisfaction", "Non-stream generation has no TTFT", "No business orders are written", "Active or unattempted scenarios are incomplete, never passed", "Selected retries do not replace previous full-run evidence"], activeScenario, unattempted: selectedCases.map(row => row.id).filter(id => id !== activeScenario && !results.some(row => row.id === id)), scenarioCount: results.length, expectedCount: selectedCases.length, complete: results.length === selectedCases.length && activeScenario === null, scenarioPassRate: results.length ? results.filter(r => r.passed).length/results.length : null, generationSuccessRate: results.length ? results.filter(r => r.run.status === "completed").length/results.length : null, feedbackSavedCount: results.filter(r => r.feedbackSaved).length, p50Ms: percentile(results.map(r => r.run.duration_ms), .5), p95Ms: percentile(results.map(r => r.run.duration_ms), .95), toolErrorCount: results.reduce((sum,r) => sum+r.run.tool_error_count,0), results };
    writeFileSync(`${folder}/${stamp}.json`, JSON.stringify(report, null, 2)+"\n");
    writeFileSync(`${folder}/${stamp}.md`, [`# Feature05 live evaluation`, `Mode: ${report.mode}`, `Generated: ${report.generatedAt}`, `Completed: ${results.length}/${selectedCases.length}; catalog: ${liveCases.length}; active: ${activeScenario ?? "none"}`, `Scenario pass rate: ${report.scenarioPassRate ?? "unknown"}; generation success: ${report.generationSuccessRate ?? "unknown"}`, `P50/P95: ${report.p50Ms ?? "unknown"}/${report.p95Ms ?? "unknown"} ms; tool errors: ${report.toolErrorCount}; feedback saved: ${report.feedbackSavedCount}/${results.length}`, "", "| Scenario | Passed | Trace | Status | Input/output tokens | Cost USD | Failures |", "| --- | --- | --- | --- | --- | --- | --- |", ...results.map(row => `| ${row.id} | ${row.passed} | ${row.run.trace_id} | ${row.run.status} | ${row.run.input_tokens ?? "unknown"}/${row.run.output_tokens ?? "unknown"} | ${row.costUSD ?? "unknown"} | ${row.failures.join(", ")} |`), "", ...results.filter(row => row.diagnostic).map(row => `${row.id} diagnostic: ${JSON.stringify(row.diagnostic)}`), "", ...report.limitations.map(value => `- ${value}`), ""].join("\n"));
  };
  saveReport();
  for (const row of selectedCases) {
    activeScenario = row.id; saveReport();
    const source = createEvaluationDataSource();
    if ("inventory" in row && row.inventory === "empty") source.listCabins = async () => [];
    if ("inventory" in row && row.inventory === "conflict") source.getConflictingCabinIds = async () => [1];
    if ("inventory" in row && row.inventory === "error") source.listCabins = async () => { throw new Error("Synthetic tool failure"); };
    const run = createRunObserver({ surface: "concierge", model: configuration.modelId, promptVersion: `concierge-${createHash("sha256").update(CONCIERGE_INSTRUCTIONS).digest("hex").slice(0,12)}` });
    const agent = createConciergeAgent({ observer: run, tools: createCabinTools(source), policySearchTool: tool({ description: "Search synthetic hotel policy sources", inputSchema: z.object({ question: z.string() }), execute: async () => ({ kind: "policy-search" as const, status: "insufficient-evidence" as const, answerContext: "" as const, citations: [], truncated: false as const }) }) as never });
    let passed = false;
    let checks: Record<string, boolean> = {};
    const failures: string[] = [];
    let diagnostic: ReturnType<typeof safeErrorDiagnostic> | null = null;
    try {
      const result = await agent.generate({ messages: [...(row.previous ? [{ role: "user" as const, content: row.previous }, { role: "assistant" as const, content: "Please review those dates." }] : []), { role: "user" as const, content: row.prompt }], timeout: { totalMs: 90_000 } });
      const calls = result.steps.flatMap(step => step.toolCalls);
      checks = assessLiveResult(row, { text: result.text, calls, outputs: result.steps.flatMap(step => step.toolResults), toolErrors: result.steps.flatMap(step => step.content).filter(part => part.type === "tool-error").length });
      failures.push(...Object.entries(checks).filter(([, ok]) => !ok).map(([name]) => name));
      passed = failures.length === 0;
      if (result.finishReason === "error") { run.mark("failed", "provider-unavailable"); passed = false; failures.push("generation-error-finish"); }
    } catch (error) { diagnostic = safeErrorDiagnostic(error); const timeout = diagnostic.category === "timeout"; run.mark(timeout ? "timeout" : "failed", timeout ? "timeout" : "provider-unavailable"); failures.push(timeout ? "generation-timeout" : "generation-failed"); }
    const record = await run.finish();
    const stored = await db.from("ai_runs").select("trace_id").eq("trace_id", run.traceId).abortSignal(AbortSignal.timeout(10_000)).maybeSingle();
    const token = issueFeedbackToken(run.traceId, "concierge");
    let feedbackSaved = false;
    try { const response = token ? await feedback(new Request("http://localhost/api/ai/feedback", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ traceId: run.traceId, token, rating: passed ? "helpful" : "not-helpful" }) })) : null; feedbackSaved = response?.status === 200; } catch { failures.push("feedback-storage-failed"); }
    const price = prices?.models[configuration.modelId];
    const costUSD = price && record.input_tokens !== null && record.output_tokens !== null ? (record.input_tokens * price.inputPerMillion + record.output_tokens * price.outputPerMillion)/1_000_000 : null;
    const persisted = Boolean(stored.data) && !stored.error;
    if (!persisted) failures.push("run-not-persisted");
    if (!feedbackSaved) failures.push("feedback-not-persisted");
    results.push({ id: row.id, passed, checks, failures, diagnostic, run: record, persisted, feedbackSaved, costUSD });
    activeScenario = null; saveReport();
  }
  expect(results.filter(row => !row.passed || !row.persisted || !row.feedbackSaved).map(row => row.id)).toEqual([]);
});
