begin;

-- Legacy quoted camelCase columns are intentional: both existing frontends
-- consume this contract. A later API-versioned migration can move to snake_case.
create extension if not exists btree_gist with schema extensions;

create table public.cabins (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null unique,
  "maxCapacity" integer not null,
  "regularPrice" numeric(10, 2) not null,
  discount numeric(10, 2) not null default 0,
  image text not null,
  description text not null,
  constraint cabins_name_not_blank check (btrim(name) <> ''),
  constraint cabins_capacity_positive check ("maxCapacity" > 0),
  constraint cabins_regular_price_positive check ("regularPrice" > 0),
  constraint cabins_discount_valid check (
    discount >= 0 and discount <= "regularPrice"
  ),
  constraint cabins_image_not_blank check (btrim(image) <> ''),
  constraint cabins_description_not_blank check (btrim(description) <> '')
);

create table public.guests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "fullName" text not null,
  email text not null unique,
  "nationalID" text,
  nationality text,
  "countryFlag" text,
  constraint guests_full_name_not_blank check (btrim("fullName") <> ''),
  constraint guests_email_not_blank check (btrim(email) <> ''),
  constraint guests_national_id_not_blank check (
    "nationalID" is null or btrim("nationalID") <> ''
  )
);

create table public.settings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "minBookingLength" integer not null,
  "maxBookingLength" integer not null,
  "maxGuestsPerBooking" integer not null,
  "breakfastPrice" numeric(10, 2) not null,
  constraint settings_singleton check (id = 1),
  constraint settings_min_booking_length_positive check (
    "minBookingLength" > 0
  ),
  constraint settings_booking_length_range_valid check (
    "maxBookingLength" >= "minBookingLength"
  ),
  constraint settings_max_guests_positive check (
    "maxGuestsPerBooking" > 0
  ),
  constraint settings_breakfast_price_positive check ("breakfastPrice" > 0)
);

create table public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "startDate" timestamptz not null,
  "endDate" timestamptz not null,
  "numNights" integer not null,
  "numGuests" integer not null,
  "cabinPrice" numeric(12, 2) not null,
  "extrasPrice" numeric(12, 2) not null default 0,
  "totalPrice" numeric(12, 2) not null,
  status text not null default 'unconfirmed',
  "hasBreakfast" boolean not null default false,
  observations text not null default '',
  "isPaid" boolean not null default false,
  "cabinId" bigint not null,
  "guestId" bigint not null,
  constraint bookings_dates_valid check ("endDate" > "startDate"),
  constraint bookings_num_nights_positive check ("numNights" > 0),
  constraint bookings_num_guests_positive check ("numGuests" > 0),
  constraint bookings_prices_non_negative check (
    "cabinPrice" >= 0 and "extrasPrice" >= 0 and "totalPrice" >= 0
  ),
  constraint bookings_total_price_consistent check (
    "totalPrice" = "cabinPrice" + "extrasPrice"
  ),
  constraint bookings_stay_length_consistent check (
    "endDate" = "startDate" + make_interval(days => "numNights")
  ),
  constraint bookings_status_valid check (
    status in ('unconfirmed', 'checked-in', 'checked-out', 'cancelled')
  ),
  constraint bookings_cabin_id_fkey foreign key ("cabinId")
    references public.cabins(id) on update restrict on delete restrict,
  constraint bookings_guest_id_fkey foreign key ("guestId")
    references public.guests(id) on update restrict on delete restrict
);

alter table public.bookings
  add constraint bookings_no_overlapping_active_stays
  exclude using gist (
    "cabinId" with =,
    tstzrange("startDate", "endDate", '[)') with &&
  )
  where (status <> 'cancelled');

-- Foreign-key support and the concrete dashboard/customer query shapes.
create index bookings_cabin_id_idx on public.bookings ("cabinId");
create index bookings_guest_history_idx
  on public.bookings ("guestId", "startDate");
create index bookings_created_at_idx
  on public.bookings (created_at desc);
create index bookings_status_created_at_idx
  on public.bookings (status, created_at desc);
create index bookings_active_availability_idx
  on public.bookings ("cabinId", "startDate", "endDate")
  where (status <> 'cancelled');
create index bookings_unconfirmed_start_idx
  on public.bookings ("startDate")
  where (status = 'unconfirmed');
create index bookings_checked_in_end_idx
  on public.bookings ("endDate")
  where (status = 'checked-in');

alter table public.cabins enable row level security;
alter table public.guests enable row level security;
alter table public.settings enable row level security;
alter table public.bookings enable row level security;

-- New Supabase projects no longer expose public tables automatically. Keep
-- grants and RLS together so Data API access is explicit and reviewable.
revoke all privileges on table public.cabins from public, anon, authenticated, service_role;
revoke all privileges on table public.guests from public, anon, authenticated, service_role;
revoke all privileges on table public.settings from public, anon, authenticated, service_role;
revoke all privileges on table public.bookings from public, anon, authenticated, service_role;

revoke all privileges on sequence public.cabins_id_seq from public, anon, authenticated, service_role;
revoke all privileges on sequence public.guests_id_seq from public, anon, authenticated, service_role;
revoke all privileges on sequence public.settings_id_seq from public, anon, authenticated, service_role;
revoke all privileges on sequence public.bookings_id_seq from public, anon, authenticated, service_role;

grant select on table public.cabins, public.settings to anon;
grant select ("startDate", "endDate", status, "cabinId")
  on table public.bookings to anon;

grant select, insert, update, delete
  on table public.cabins, public.guests, public.settings, public.bookings
  to authenticated;
grant usage, select
  on sequence public.cabins_id_seq, public.guests_id_seq,
    public.settings_id_seq, public.bookings_id_seq
  to authenticated;

grant select, insert, update, delete
  on table public.cabins, public.guests, public.settings, public.bookings
  to service_role;
grant usage, select
  on sequence public.cabins_id_seq, public.guests_id_seq,
    public.settings_id_seq, public.bookings_id_seq
  to service_role;

create policy cabins_public_read
  on public.cabins for select to anon
  using (true);

create policy settings_public_read
  on public.settings for select to anon
  using (true);

create policy bookings_public_availability_read
  on public.bookings for select to anon
  using (status <> 'cancelled');

create policy cabins_admin_all
  on public.cabins for all to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy guests_admin_all
  on public.guests for all to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy settings_admin_all
  on public.settings for all to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy bookings_admin_all
  on public.bookings for all to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

insert into storage.buckets (id, name, public)
values ('cabin-images', 'cabin-images', true)
on conflict (id) do update
set name = excluded.name,
    public = excluded.public;

-- Public buckets expose object bytes by URL without a SELECT policy. Listing
-- and every mutation remain protected by storage.objects RLS.
create policy cabin_images_admin_select
  on storage.objects for select to authenticated
  using (
    bucket_id = 'cabin-images'
    and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

create policy cabin_images_admin_insert
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'cabin-images'
    and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

create policy cabin_images_admin_update
  on storage.objects for update to authenticated
  using (
    bucket_id = 'cabin-images'
    and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  )
  with check (
    bucket_id = 'cabin-images'
    and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

create policy cabin_images_admin_delete
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'cabin-images'
    and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

commit;
